eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
spring:
  application:
    name: ServiceEureka
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: '123456'
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.100.212:3306/imut_manage?useUnicode=true&characterEncoding=UTF-8
    username: root
  rabbitmq:
    host: 192.168.26.128
    username: hadoop
    password: 123456
    port: 5672
